language: rust
cache:    cargo

env:
  global:
    - PROJECT_NAME=djs
    - RUST_BACKTRACE: full

addons:
  apt:
    packages:
      # Needed for completion-function test
      - zsh
      - libssl-dev

matrix:
  fast_finish: true
  include:
    # Nightly channel.
    # (All *nix releases are done on the nightly channel to take advantage
    # of the regex library's multiple pattern SIMD search.)
    - os: linux
      rust: nightly
      env: TARGET=i686-unknown-linux-musl
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: nightly
      env: TARGET=arm-unknown-linux-gnueabihf GCC_VERSION=4.8
      addons:
        apt:
          packages:
          - gcc-4.8-arm-linux-gnueabihf
          - binutils-arm-linux-gnueabihf
          - libc6-armhf-cross
          - libc6-dev-armhf-cross
    # Beta channel.
    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-musl
    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-gnu
    # Minimum Rust supported channel.
    - os: linux
      rust: 1.17.0
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: 1.17.0
      env: TARGET=x86_64-unknown-linux-musl
    - os: linux
      rust: 1.17.0
      env: TARGET=arm-unknown-linux-gnueabihf GCC_VERSION=4.8
      addons:
        apt:
          packages:
          - gcc-4.8-arm-linux-gnueabihf
          - binutils-arm-linux-gnueabihf
          - libc6-armhf-cross
          - libc6-dev-armhf-cross

before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

before_deploy:
  - bash ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
      secure: "my-key"
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*
  # don't delete the artifacts from previous phases
  skip_cleanup: true
  # deploy when a new tag is pushed
  on:
    # channel to use to produce the release artifacts
    # NOTE make sure you only release *once* per target
    # TODO you may want to pick a different channel
    condition: $TRAVIS_RUST_VERSION = nightly
    tags: true

branches:
  only:
    # Pushes and PR to the master branch
    - master
    # IMPORTANT Ruby regex to match tags. Required, or travis won't trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^\d+\.\d+\.\d+.*$/

notifications:
  email:
    on_success: never
