[package]
name = "djs"
version = "0.1.0"
authors = ["Trever Shick <trevershick@gmail.com>"]

[dependencies]
clap = "2.29.0"
log = "0.3.8"
env_logger = "0.4.3"
reqwest = "0.8.2"
serde-xml-rs = "0.2.1"
serde_derive = "1.0.25"
serde = "1.0.25"
